### ISSUE TITLE
Set plugins per file not globally

### ISSUE THREAD

**Issue by ai** [postcss/postcss-use#1]
Right now we change entire `processor.plugin` as result plugins from one file and affect to other. Is it correct behaviour?

**Comment by ben-eb** [comment]
I wasn't aware that PostCSS had multiple file support?

**Comment by ai** [comment]
One processor can be used to many files.

```js
let processor = postcss(plugins);
processor.process(css1);
processor.process(css2);
```

**Comment by ai** [comment]
So, I expect from Gulp/Grunt runners to use one processor for many files.

**Comment by ben-eb** [comment]
OK. Do you think we could just reset result.processor.plugins on initialize?

**Comment by ai** [comment]
Yeap, nice solution, I missed it ;)

**Comment by andreypopp** [comment]
I think the behaviour where we allow configuring global processing pipeline from modules is dangerous and non-modular. Some module could activate processor which results in nonsense in another module. Instead I'd like to see `@use` only has effect on the same module it appears.

**Comment by ben-eb** [comment]
This module is intended to use PostCSS via a browser environment, where the end user doesn't have control over the PostCSS instance except by the `@use` directive. Using PostCSS and configuring the plugins yourself is the best way to use it, especially as this module cannot accept functions as parameters.

**Comment by ai** [comment]
@ben-eb desktop CodeKit users will be happy because this plugin too :).

**Comment by ben-eb** [comment]
Good call. :smiley:

**Comment by MoOx** [comment]
Also, maybe you can use .source to check origin (file). Hacky...

**Comment by ai** [comment]
What about adding cleaner after itself and all added plugins?

```
let origin = result.plugins.slice();
css.eachAtRule('use', (rule) => result.plugins.push(loadPlugin(rule)) );
result.plugins.push((css, result) => {
    result.plugins = origin;
});
```

**Comment by ai** [comment]
@ben-eb maybe we should set a name for cleaner plugin? It will be good for debug. Like `postcss-use#cleaner`

**Comment by ben-eb** [comment]
Should I use the plugin API for this?

**Comment by ai** [comment]
Yeap, I suggest `postcss-use#cleaner` name

**Comment by ben-eb** [comment]
I like `reset` a bit better. https://github.com/postcss/postcss-use/blob/master/index.js#L94-L98

**Comment by ai** [comment]
@ben-eb cool

**Comment by MoOx** [comment]
You can add in the README how to _really_ use this per files: using postcss-import plugins option https://github.com/postcss/postcss-import#plugins

**Comment by morishitter** [comment]
@ben-eb 
How can I call `postcss-use#reset`? Please give me a sample code.
Thanks :)

**Comment by ben-eb** [comment]
@morishitter What's the use case? Currently it is just an internal feature.

**Comment by morishitter** [comment]
@ben-eb I see. I would like to make scope to adapt `postcss-use`. For example,

```css
@use postcss-discard-comments(removeAll: true);
/* Only this area adapt this plugin */
h1 {
    color: red
}
@reset postcss-discard-comments

**Comment by ben-eb** [comment]
Does https://github.com/postcss/postcss-plugin-context solve this use case?

**Comment by morishitter** [comment]
`postcss-plugin-context` is an awesome plugin! I will try with it. Thanks :D
