### ISSUE TITLE
Does this automatically load anything by default?

### ISSUE THREAD

**Issue by corysimmons** [postcss/postcss-use#13]
Getting some weird calc reduction on CodePen. Apparently they use this plugin to load PostCSS plugins. Curious if this plugin automatically loads anything like CSSNext or postcss-calc (or for that matter anything)...

**Comment by ben-eb** [comment]
Nope. CodePen use their own list of plugins.

https://github.com/postcss/postcss-use/blob/master/package.json#L33-L36

**Comment by corysimmons** [comment]
Thanks @ben-eb
