### ISSUE TITLE
Optional modules

### ISSUE THREAD

**Issue by ai** [postcss/postcss-use#4]
`modules` is important for CodePen. But if we use this plugin inside team, where everyone has access to JS, security is not a question.

Maybe we should add `modules: "*"`.

**Comment by ben-eb** [comment]
Should we consider this a breaking change?

**Comment by ai** [comment]
I think it is API extending

**Comment by ben-eb** [comment]
We can make the module still throw if the `modules` option is `undefined`. A user should have to explicitly set the level of security they are comfortable with.

**Comment by ai** [comment]
Agree, it should be explicit.

**Comment by ben-eb** [comment]
Released as `1.2.0`.
